### ISSUE TITLE
Missing dependencies to build bitcoin

### ISSUE THREAD

**Issue by StrobFX** [KomodoPlatform/Documentation#48]
When following setup-Komodo-Notary-Node.md, bitcoin is missing dependencies to be able to build (libtool all dev and libevent-dev I think).
If I installed the ones suggested here it works:
https://github.com/KomodoPlatform/komodo/wiki/Setup-Komodo-Notary-Node

**Comment by tonymorony** [comment]
Thank you for issue

Yes, I've noticed too that one or two packages are missing. Will re-test that and open PR with needed deps shortly so newcomers will not be confused.

 Please note that Github wiki is deprecated and Documentation is using instead because it's much easier to collaborate and everybody can contribute by PR opening into this repo.

https://docs.komodoplatform.com/notary/setup-Komodo-Notary-Node.html is relevant page (https://github.com/KomodoPlatform/Documentation/blob/master/docs/notary/setup-Komodo-Notary-Node.md)
